Upload/Download actions
USACE/cc-java-sdk-depricated pull request #6
Opened 2023-08-08 17:40 UTC by slawler

This PR simplifies the gradle build processs

Adds:
- options to configure the cc store's root and manifest id variables outside of environmental variables
- error handling for downloading inputs

Modifies:
- plugin manager to specify the cc store outside environment variables
- docker files and gradle build process

Removes:
- publishing to https://maven.pkg.github.com/USACE/cc-java-sdk

2023-08-08 18:05 UTC, HenryGeorgist requested changes
i think the biggest requests are allowing the package to continue to be pushed to maven central and making the setters for root and manifest to be package private. ideally the construction of that option on get instance would also be package private and then an auxilary main for running local would be leveraged if that can satisfy the workflow.

2023-08-08 18:05 UTC, HenryGeorgist commented on Dockerfile
> +RUN gradle build
im not sure i like this. i dev inside this container, i dont really like it running build all the time. convince me

2023-08-08 18:05 UTC, HenryGeorgist commented on README.md
> +This library can be built and containerized with Docker:
not sure what advantage this adds. it is designed to be a dependency for people developing plugins, not designed to be run in a container by itself. am i missing somethign?

2023-08-08 18:05 UTC, HenryGeorgist commented on build.gradle
> +    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
nice.

2023-08-08 18:05 UTC, HenryGeorgist commented on build.gradle
>      group 'mil.army.usace.hec'
I need to continue to support the github package, we can set up sub modules but i still need the ability to publish  artifacts on release through github actions for other use cases.

2023-08-08 18:05 UTC, HenryGeorgist commented on src/main/java/usace/cc/plugin/CcStoreS3.java
> +    public void setManifestId(String manifestId) {
this is a deviation from the other sdk's it is also something that could cause confusion. i think i understand the use case and the advantages this creates for the specific use case, but i am concerned a public method is dangerous. can we consider package private with an auxilary main for local developmen?

2023-08-08 18:05 UTC, HenryGeorgist commented on src/main/java/usace/cc/plugin/CcStoreS3.java
> +    public void setRoot(String root) {
same as above

2023-08-09 13:48 UTC, slawler commented on Dockerfile
> +RUN gradle build
Agree, will remove.

2023-08-09 13:56 UTC, slawler commented on src/main/java/usace/cc/plugin/CcStoreS3.java
> +    public void setRoot(String root) {
done

2023-08-09 13:56 UTC, slawler commented on src/main/java/usace/cc/plugin/CcStoreS3.java
> +    public void setManifestId(String manifestId) {
updated tp private

2023-08-09 19:00 UTC, andrewsongj commented on src/main/java/usace/cc/plugin/CcStoreS3.java
> +    public void setManifestId(String manifestId) {
To provide context, we are trying to implement command line args inside the hms-runner so that we can configure these root and manifest variables from the hms runner. We have made the setter methods inside CcStoreS3.java into package private-- I was just wondering what the auxiliary main method would be for?

2024-06-28 19:17 UTC, closed without merging

2024-06-28 19:17 UTC, HenryGeorgist commented
outdated changes